/**
 * API Usuarios
 * Documentación de la API de Usuarios
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: alejandromonsivais367@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiUsuarios);
  }
}(this, function(expect, ApiUsuarios) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiUsuarios.UsuarioInput();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsuarioInput', function() {
    it('should create an instance of UsuarioInput', function() {
      // uncomment below and update the code to test UsuarioInput
      //var instance = new ApiUsuarios.UsuarioInput();
      //expect(instance).to.be.a(ApiUsuarios.UsuarioInput);
    });

    it('should have the property usuarioNombre (base name: "usuario_nombre")', function() {
      // uncomment below and update the code to test the property usuarioNombre
      //var instance = new ApiUsuarios.UsuarioInput();
      //expect(instance).to.be();
    });

    it('should have the property usuarioApellido (base name: "usuario_apellido")', function() {
      // uncomment below and update the code to test the property usuarioApellido
      //var instance = new ApiUsuarios.UsuarioInput();
      //expect(instance).to.be();
    });

    it('should have the property usuarioUsuario (base name: "usuario_usuario")', function() {
      // uncomment below and update the code to test the property usuarioUsuario
      //var instance = new ApiUsuarios.UsuarioInput();
      //expect(instance).to.be();
    });

    it('should have the property usuarioClave (base name: "usuario_clave")', function() {
      // uncomment below and update the code to test the property usuarioClave
      //var instance = new ApiUsuarios.UsuarioInput();
      //expect(instance).to.be();
    });

    it('should have the property usuarioEmail (base name: "usuario_email")', function() {
      // uncomment below and update the code to test the property usuarioEmail
      //var instance = new ApiUsuarios.UsuarioInput();
      //expect(instance).to.be();
    });

  });

}));
