/**
 * API Usuarios
 * Documentación de la API de Usuarios
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: alejandromonsivais367@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Usuario model module.
 * @module model/Usuario
 * @version 1.0.0
 */
class Usuario {
    /**
     * Constructs a new <code>Usuario</code>.
     * @alias module:model/Usuario
     */
    constructor() { 
        
        Usuario.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Usuario</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Usuario} obj Optional instance to populate.
     * @return {module:model/Usuario} The populated <code>Usuario</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Usuario();

            if (data.hasOwnProperty('usuario_id')) {
                obj['usuario_id'] = ApiClient.convertToType(data['usuario_id'], 'Number');
            }
            if (data.hasOwnProperty('usuario_nombre')) {
                obj['usuario_nombre'] = ApiClient.convertToType(data['usuario_nombre'], 'String');
            }
            if (data.hasOwnProperty('usuario_apellido')) {
                obj['usuario_apellido'] = ApiClient.convertToType(data['usuario_apellido'], 'String');
            }
            if (data.hasOwnProperty('usuario_usuario')) {
                obj['usuario_usuario'] = ApiClient.convertToType(data['usuario_usuario'], 'String');
            }
            if (data.hasOwnProperty('usuario_email')) {
                obj['usuario_email'] = ApiClient.convertToType(data['usuario_email'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Usuario</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Usuario</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['usuario_nombre'] && !(typeof data['usuario_nombre'] === 'string' || data['usuario_nombre'] instanceof String)) {
            throw new Error("Expected the field `usuario_nombre` to be a primitive type in the JSON string but got " + data['usuario_nombre']);
        }
        // ensure the json data is a string
        if (data['usuario_apellido'] && !(typeof data['usuario_apellido'] === 'string' || data['usuario_apellido'] instanceof String)) {
            throw new Error("Expected the field `usuario_apellido` to be a primitive type in the JSON string but got " + data['usuario_apellido']);
        }
        // ensure the json data is a string
        if (data['usuario_usuario'] && !(typeof data['usuario_usuario'] === 'string' || data['usuario_usuario'] instanceof String)) {
            throw new Error("Expected the field `usuario_usuario` to be a primitive type in the JSON string but got " + data['usuario_usuario']);
        }
        // ensure the json data is a string
        if (data['usuario_email'] && !(typeof data['usuario_email'] === 'string' || data['usuario_email'] instanceof String)) {
            throw new Error("Expected the field `usuario_email` to be a primitive type in the JSON string but got " + data['usuario_email']);
        }

        return true;
    }


}



/**
 * @member {Number} usuario_id
 */
Usuario.prototype['usuario_id'] = undefined;

/**
 * @member {String} usuario_nombre
 */
Usuario.prototype['usuario_nombre'] = undefined;

/**
 * @member {String} usuario_apellido
 */
Usuario.prototype['usuario_apellido'] = undefined;

/**
 * @member {String} usuario_usuario
 */
Usuario.prototype['usuario_usuario'] = undefined;

/**
 * @member {String} usuario_email
 */
Usuario.prototype['usuario_email'] = undefined;






export default Usuario;

