/**
 * API Usuarios
 * Documentación de la API de Usuarios
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: alejandromonsivais367@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Usuario from './Usuario';

/**
 * The UsuarioGet200Response model module.
 * @module model/UsuarioGet200Response
 * @version 1.0.0
 */
class UsuarioGet200Response {
    /**
     * Constructs a new <code>UsuarioGet200Response</code>.
     * @alias module:model/UsuarioGet200Response
     * @param {(module:model/Usuario|module:model/[Usuario])} instance The actual instance to initialize UsuarioGet200Response.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "Usuario") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                Usuario.validateJSON(instance); // throw an exception if no match
                // create Usuario from JS object
                this.actualInstance = Usuario.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into Usuario
            errorMessages.push("Failed to construct Usuario: " + err)
        }

        try {
            if (typeof instance === "[Usuario]") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                [Usuario].validateJSON(instance); // throw an exception if no match
                // create [Usuario] from JS object
                this.actualInstance = [Usuario].constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into [Usuario]
            errorMessages.push("Failed to construct [Usuario]: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `UsuarioGet200Response` with oneOf schemas Usuario, [Usuario]. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `UsuarioGet200Response` with oneOf schemas Usuario, [Usuario]. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>UsuarioGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsuarioGet200Response} obj Optional instance to populate.
     * @return {module:model/UsuarioGet200Response} The populated <code>UsuarioGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        return new UsuarioGet200Response(data);
    }

    /**
     * Gets the actual instance, which can be <code>Usuario</code>, <code>[Usuario]</code>.
     * @return {(module:model/Usuario|module:model/[Usuario])} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>Usuario</code>, <code>[Usuario]</code>.
     * @param {(module:model/Usuario|module:model/[Usuario])} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = UsuarioGet200Response.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of UsuarioGet200Response from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/UsuarioGet200Response} An instance of UsuarioGet200Response.
     */
    static fromJSON = function(json_string){
        return UsuarioGet200Response.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {Number} usuario_id
 */
UsuarioGet200Response.prototype['usuario_id'] = undefined;

/**
 * @member {String} usuario_nombre
 */
UsuarioGet200Response.prototype['usuario_nombre'] = undefined;

/**
 * @member {String} usuario_apellido
 */
UsuarioGet200Response.prototype['usuario_apellido'] = undefined;

/**
 * @member {String} usuario_usuario
 */
UsuarioGet200Response.prototype['usuario_usuario'] = undefined;

/**
 * @member {String} usuario_email
 */
UsuarioGet200Response.prototype['usuario_email'] = undefined;


UsuarioGet200Response.OneOf = ["Usuario", "[Usuario]"];

export default UsuarioGet200Response;

